# Generated by Django 3.1.6 on 2021-03-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsaAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('user_type', models.IntegerField(choices=[(1, 'Student'), (2, 'Alumni'), (3, 'Staff'), (4, 'Anonymous')])),
                ('date_of_passing', models.IntegerField()),
                ('hometown', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')])),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('work_place', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('linkedin_id', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'CSAALL',
            },
        ),
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(upload_to='notices')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('notice_pdf', models.FileField(upload_to='notices')),
            ],
            options={
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
