# Generated by Django 3.1.6 on 2021-04-01 06:31

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsaAll',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.IntegerField(choices=[(1, 'Student'), (2, 'Alumni'), (3, 'Staff'), (4, 'Anonymous')])),
                ('year_of_passing', models.IntegerField()),
                ('hometown', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')])),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('work_place', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('linkedin_id', models.CharField(max_length=200, null=True, unique=True)),
                ('github_id', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'CSAALL',
            },
        ),
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('event_id', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_image', models.ImageField(upload_to='events')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('notice_id', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('notice_pdf', models.FileField(upload_to='notices')),
            ],
            options={
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='Project_category_model',
            fields=[
                ('category_id', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='project_specification_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_platform', models.CharField(max_length=100)),
                ('spec_languages', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.DateField()),
                ('field_of_interest', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6)),
                ('projects_done', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6)),
                ('skills', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csaall')),
            ],
        ),
        migrations.CreateModel(
            name='Project_model',
            fields=[
                ('project_id', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_subtitle', models.CharField(max_length=100)),
                ('project_domain', models.CharField(max_length=100)),
                ('project_logo', models.ImageField(upload_to='project_logos')),
                ('project_description', models.CharField(max_length=300)),
                ('author_id', models.ManyToManyField(to='api.Student_model')),
                ('categories', models.ManyToManyField(to='api.Project_category_model')),
                ('project_specification', models.ManyToManyField(to='api.project_specification_model')),
            ],
        ),
    ]
