# Generated by Django 3.1.6 on 2021-03-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_csaall_eventsmodel_noticemodel_userauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_category_model',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_model',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_subtitle', models.CharField(max_length=100)),
                ('project_domain', models.CharField(max_length=100)),
                ('project_logo', models.ImageField(upload_to='project_logos')),
                ('project_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='project_specification_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_platform', models.CharField(max_length=100)),
                ('spec_languages', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.DateField()),
                ('field_of_interest', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6)),
                ('projects_done', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6)),
                ('skills', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAuth',
        ),
        migrations.RenameField(
            model_name='csaall',
            old_name='date_of_passing',
            new_name='year_of_passing',
        ),
        migrations.RemoveField(
            model_name='csaall',
            name='id',
        ),
        migrations.RemoveField(
            model_name='csaall',
            name='username',
        ),
        migrations.AddField(
            model_name='csaall',
            name='github_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='csaall',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticemodel',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csaall',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='thumbnail_image',
            field=models.ImageField(upload_to='events'),
        ),
        migrations.AddField(
            model_name='student_model',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csaall'),
        ),
        migrations.AddField(
            model_name='project_model',
            name='author_id',
            field=models.ManyToManyField(to='api.Student_model'),
        ),
        migrations.AddField(
            model_name='project_model',
            name='categories',
            field=models.ManyToManyField(to='api.Project_category_model'),
        ),
        migrations.AddField(
            model_name='project_model',
            name='project_specification',
            field=models.ManyToManyField(to='api.project_specification_model'),
        ),
    ]
