# Generated by Django 3.1.6 on 2021-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210313_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='noticemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='event_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='noticemodel',
            name='notice_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project_category_model',
            name='category_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project_model',
            name='project_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
