# Generated by Django 3.1.6 on 2021-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210313_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='event_id',
            field=models.AutoField(default='', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticemodel',
            name='notice_id',
            field=models.AutoField(default='', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project_category_model',
            name='category_id',
            field=models.AutoField(default='', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project_model',
            name='project_id',
            field=models.AutoField(default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
